# online-judge product config

################################ datasource connector config start ###############################
spring:
  datasource:
    url: jdbc:mysql://121.36.21.111:3306/onlinejudge?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123123
################################ datasource connector config end #################################

############################### Redis config start ###############################
---
spring:
  redis:
    database: 0
    host: 121.36.21.111
    password:
    port: 6379
############################### Redis config end ##################################

############################### kafka config start ###############################
---
spring:
  kafka:
    # kafka代理地址
    bootstrap-servers: 39.97.183.91:9092
############################### kafka config end ###############################